name: Release

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Build
        run: cargo build --release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: not-locking.exe
          path: target/release/not-locking.exe